AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification
Resources:
  PhotoAlbumS3B2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: assignment2-kerem-nana-photos
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: assignment2-kerem-nana-photos
      PolicyDocument:
        Version: '2012-10-17'
        Id: MyPolicy
        Statement:
        - Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: arn:aws:s3:::assignment2-kerem-nana-photos/*
        - Effect: Allow
          Principal: '*'
          Action: s3:PutObject
          Resource: arn:aws:s3:::assignment2-kerem-nana-photos/*
  LF1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos
      Description: 'Create indexes for photos'
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::395718007070:role/service-role/rekognition
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: PhotoAlbumS3B2
            Events:
            - s3:ObjectCreated:Put
  LF2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./search-photos
      Description: Function for searching for indexed photos
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::395718007070:role/service-role/search-photos-role-hw74j5wv
      Environment:
        Variables:
          Region: us-east-1
  OpenAPI:
    Type: 'AWS::ApiGateway::RestApi'
    DeletionPolicy: Retain
    Properties:
      Description: AI Photo Album App API
      Name: TestAPI2
      CloneFrom: q9fue4di88
  OpenSearchAlbumOS1:
    Type: 'AWS::OpenSearchService::Domain'
    DeletionPolicy: Retain
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'es:*'
            Resource: 'arn:aws:es:us-east-1:395718007070:domain/photos2/*'
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: KeremNana
          MasterUserPassword: KeremNana1!
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: >-
          arn:aws:kms:us-east-1:395718007070:key/79cb5455-3856-4910-aaf9-855a231c5458
      DomainName: photos2
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 1
        InstanceType: t3.small.search
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
